// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: grpc_proto_files/upvote.proto

package upvote_pb

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpvoteType int32

const (
	UpvoteType_upvote   UpvoteType = 0
	UpvoteType_downvote UpvoteType = 1
)

// Enum value maps for UpvoteType.
var (
	UpvoteType_name = map[int32]string{
		0: "upvote",
		1: "downvote",
	}
	UpvoteType_value = map[string]int32{
		"upvote":   0,
		"downvote": 1,
	}
)

func (x UpvoteType) Enum() *UpvoteType {
	p := new(UpvoteType)
	*p = x
	return p
}

func (x UpvoteType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpvoteType) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_proto_files_upvote_proto_enumTypes[0].Descriptor()
}

func (UpvoteType) Type() protoreflect.EnumType {
	return &file_grpc_proto_files_upvote_proto_enumTypes[0]
}

func (x UpvoteType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpvoteType.Descriptor instead.
func (UpvoteType) EnumDescriptor() ([]byte, []int) {
	return file_grpc_proto_files_upvote_proto_rawDescGZIP(), []int{0}
}

type AddUpvoteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommentId  string     `protobuf:"bytes,1,opt,name=commentId,proto3" json:"commentId,omitempty"`
	UpvoteType UpvoteType `protobuf:"varint,2,opt,name=upvoteType,proto3,enum=LearningGRPC.UpvoteType" json:"upvoteType,omitempty"`
}

func (x *AddUpvoteRequest) Reset() {
	*x = AddUpvoteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_files_upvote_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddUpvoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUpvoteRequest) ProtoMessage() {}

func (x *AddUpvoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_files_upvote_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUpvoteRequest.ProtoReflect.Descriptor instead.
func (*AddUpvoteRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_files_upvote_proto_rawDescGZIP(), []int{0}
}

func (x *AddUpvoteRequest) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

func (x *AddUpvoteRequest) GetUpvoteType() UpvoteType {
	if x != nil {
		return x.UpvoteType
	}
	return UpvoteType_upvote
}

type DeleteUpvoteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommentId string `protobuf:"bytes,1,opt,name=commentId,proto3" json:"commentId,omitempty"`
	UpvoteId  string `protobuf:"bytes,2,opt,name=upvoteId,proto3" json:"upvoteId,omitempty"`
}

func (x *DeleteUpvoteRequest) Reset() {
	*x = DeleteUpvoteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_files_upvote_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUpvoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUpvoteRequest) ProtoMessage() {}

func (x *DeleteUpvoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_files_upvote_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUpvoteRequest.ProtoReflect.Descriptor instead.
func (*DeleteUpvoteRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_files_upvote_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteUpvoteRequest) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

func (x *DeleteUpvoteRequest) GetUpvoteId() string {
	if x != nil {
		return x.UpvoteId
	}
	return ""
}

type UpvoteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UpvoteType string `protobuf:"bytes,2,opt,name=upvoteType,proto3" json:"upvoteType,omitempty"`
	CreatedAt  string `protobuf:"bytes,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
}

func (x *UpvoteResponse) Reset() {
	*x = UpvoteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_files_upvote_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpvoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpvoteResponse) ProtoMessage() {}

func (x *UpvoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_files_upvote_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpvoteResponse.ProtoReflect.Descriptor instead.
func (*UpvoteResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_files_upvote_proto_rawDescGZIP(), []int{2}
}

func (x *UpvoteResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpvoteResponse) GetUpvoteType() string {
	if x != nil {
		return x.UpvoteType
	}
	return ""
}

func (x *UpvoteResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_grpc_proto_files_upvote_proto protoreflect.FileDescriptor

var file_grpc_proto_files_upvote_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x66, 0x69, 0x6c,
	0x65, 0x73, 0x2f, 0x75, 0x70, 0x76, 0x6f, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0c, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x47, 0x52, 0x50, 0x43, 0x1a, 0x1b, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65,
	0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6a, 0x0a, 0x10, 0x41, 0x64,
	0x64, 0x55, 0x70, 0x76, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x0a,
	0x75, 0x70, 0x76, 0x6f, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x18, 0x2e, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x47, 0x52, 0x50, 0x43, 0x2e,
	0x55, 0x70, 0x76, 0x6f, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x75, 0x70, 0x76, 0x6f,
	0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x4f, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x55, 0x70, 0x76, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x70, 0x76, 0x6f, 0x74, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x70, 0x76, 0x6f, 0x74, 0x65, 0x49, 0x64, 0x22, 0x5e, 0x0a, 0x0e, 0x55, 0x70, 0x76, 0x6f, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x70, 0x76,
	0x6f, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x75,
	0x70, 0x76, 0x6f, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x2a, 0x26, 0x0a, 0x0a, 0x55, 0x70, 0x76, 0x6f, 0x74,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x75, 0x70, 0x76, 0x6f, 0x74, 0x65, 0x10,
	0x00, 0x12, 0x0c, 0x0a, 0x08, 0x64, 0x6f, 0x77, 0x6e, 0x76, 0x6f, 0x74, 0x65, 0x10, 0x01, 0x32,
	0xb3, 0x01, 0x0a, 0x0d, 0x55, 0x70, 0x76, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x4c, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x55, 0x70, 0x76, 0x6f, 0x74, 0x65, 0x54, 0x6f,
	0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1e, 0x2e, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69,
	0x6e, 0x67, 0x47, 0x52, 0x50, 0x43, 0x2e, 0x41, 0x64, 0x64, 0x55, 0x70, 0x76, 0x6f, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12,
	0x54, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x70, 0x76, 0x6f, 0x74, 0x65, 0x46,
	0x72, 0x6f, 0x6d, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x2e, 0x4c, 0x65, 0x61,
	0x72, 0x6e, 0x69, 0x6e, 0x67, 0x47, 0x52, 0x50, 0x43, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x55, 0x70, 0x76, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x31, 0x5a, 0x2f, 0x72, 0x65, 0x6c, 0x65, 0x6d, 0x62, 0x72,
	0x61, 0x6e, 0x64, 0x6f, 0x5f, 0x32, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f,
	0x75, 0x70, 0x76, 0x6f, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x75,
	0x70, 0x76, 0x6f, 0x74, 0x65, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_proto_files_upvote_proto_rawDescOnce sync.Once
	file_grpc_proto_files_upvote_proto_rawDescData = file_grpc_proto_files_upvote_proto_rawDesc
)

func file_grpc_proto_files_upvote_proto_rawDescGZIP() []byte {
	file_grpc_proto_files_upvote_proto_rawDescOnce.Do(func() {
		file_grpc_proto_files_upvote_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_proto_files_upvote_proto_rawDescData)
	})
	return file_grpc_proto_files_upvote_proto_rawDescData
}

var file_grpc_proto_files_upvote_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grpc_proto_files_upvote_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpc_proto_files_upvote_proto_goTypes = []interface{}{
	(UpvoteType)(0),             // 0: LearningGRPC.UpvoteType
	(*AddUpvoteRequest)(nil),    // 1: LearningGRPC.AddUpvoteRequest
	(*DeleteUpvoteRequest)(nil), // 2: LearningGRPC.DeleteUpvoteRequest
	(*UpvoteResponse)(nil),      // 3: LearningGRPC.UpvoteResponse
	(*empty.Empty)(nil),         // 4: google.protobuf.Empty
}
var file_grpc_proto_files_upvote_proto_depIdxs = []int32{
	0, // 0: LearningGRPC.AddUpvoteRequest.upvoteType:type_name -> LearningGRPC.UpvoteType
	1, // 1: LearningGRPC.UpvoteService.AddUpvoteToComment:input_type -> LearningGRPC.AddUpvoteRequest
	2, // 2: LearningGRPC.UpvoteService.DeleteUpvoteFromComment:input_type -> LearningGRPC.DeleteUpvoteRequest
	4, // 3: LearningGRPC.UpvoteService.AddUpvoteToComment:output_type -> google.protobuf.Empty
	4, // 4: LearningGRPC.UpvoteService.DeleteUpvoteFromComment:output_type -> google.protobuf.Empty
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_proto_files_upvote_proto_init() }
func file_grpc_proto_files_upvote_proto_init() {
	if File_grpc_proto_files_upvote_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_proto_files_upvote_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddUpvoteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_files_upvote_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUpvoteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_files_upvote_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpvoteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_proto_files_upvote_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_proto_files_upvote_proto_goTypes,
		DependencyIndexes: file_grpc_proto_files_upvote_proto_depIdxs,
		EnumInfos:         file_grpc_proto_files_upvote_proto_enumTypes,
		MessageInfos:      file_grpc_proto_files_upvote_proto_msgTypes,
	}.Build()
	File_grpc_proto_files_upvote_proto = out.File
	file_grpc_proto_files_upvote_proto_rawDesc = nil
	file_grpc_proto_files_upvote_proto_goTypes = nil
	file_grpc_proto_files_upvote_proto_depIdxs = nil
}
